version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install -r docs/requirements.txt
    - python docs/make_subdocs.py
    - sphinx-build -b html docs/$READTHEDOCS_LANGUAGE $READTHEDOCS_OUTPUT/html -c docs


sphinx:
   configuration: docs/conf.py

formats:
  - epub

python:
   install:
   - requirements: docs/requirements.txt