services:
  speech2motion:
    image: dlp3d/speech2motion:latest
    container_name: speech2motion
    restart: unless-stopped
    volumes:
      - ./data:/workspace/speech2motion/data
    networks:
      - dlp3d_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18084/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  audio2face:
    image: dlp3d/audio2face:latest
    container_name: audio2face
    restart: unless-stopped
    volumes:
      - ./weights:/workspace/audio2face/weights
    networks:
      - dlp3d_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18083/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: admin_password
    volumes:
      - mongodb_data:/data/db
    networks:
      - dlp3d_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  web_backend:
    image: dlp3d/web_backend:latest
    container_name: web_backend
    restart: unless-stopped
    entrypoint: ["/opt/venv/bin/python", "main.py", "--config_path", "configs/community_zh.py"]
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: web_user
      MONGODB_PASSWORD: web_password
      MONGODB_DATABASE: web_database
      MONGODB_AUTH_DATABASE: web_database
      MONGODB_ADMIN_USERNAME: admin
      MONGODB_ADMIN_PASSWORD: admin_password
    volumes:
      - ./data:/workspace/web-backend/data
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - dlp3d_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  orchestrator:
    image: dlp3d/orchestrator:latest
    container_name: orchestrator
    restart: unless-stopped
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_MEMORY_DB: memory_database
      MONGODB_MEMORY_USER: memory_user
      MONGODB_MEMORY_PASSWORD: memory_password
      MONGODB_WEB_DB: web_database
      MONGODB_WEB_USER: web_user
      MONGODB_WEB_PASSWORD: web_password
      MONGODB_ADMIN_USERNAME: admin
      MONGODB_ADMIN_PASSWORD: admin_password
      A2F_WS_URL: ws://audio2face:18083/api/v1/streaming_audio2face/ws
      S2M_WS_URL: ws://speech2motion:18084/api/v3/streaming_speech2motion/ws
      BACKEND_URL: http://web_backend:18080/api/v1/motion_keywords
    depends_on:
      mongodb:
        condition: service_healthy
      speech2motion:
        condition: service_healthy
      audio2face:
        condition: service_healthy
      web_backend:
        condition: service_healthy
    networks:
      - dlp3d_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18081/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  web_frontend:
    image:  dlp3d/web:latest
    container_name: web_frontend
    restart: unless-stopped
    environment:
      NEXT_APP_NAME: "dlp3d"
      NEXT_PUBLIC_BACKEND_HOST: "127.0.0.1"
      NEXT_PUBLIC_BACKEND_PORT: 18001
      NEXT_PUBLIC_ORCHESTRATOR_HOST: "127.0.0.1"
      NEXT_PUBLIC_ORCHESTRATOR_PORT: 18002
      NEXT_PUBLIC_LANGUAGE: "zh"
    networks:
      - dlp3d_network
    depends_on:
      - web_backend
      - orchestrator

  nginx:
    image: dlp3d/web_proxy:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "18000:18000"
      - "18001:18001"
      - "18002:18002"
    networks:
      - dlp3d_network
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web_frontend
      - orchestrator
      - web_backend

volumes:
  mongodb_data:

networks:
  dlp3d_network:
    driver: bridge
