import { env } from 'next-runtime-env'

const staticPublicEnv: Record<string, string | undefined> = {
  NEXT_PUBLIC_DEPLOY_TARGET: process.env.NEXT_PUBLIC_DEPLOY_TARGET,
  NEXT_PUBLIC_SITE_BASE_PATH: process.env.NEXT_PUBLIC_SITE_BASE_PATH,
  NEXT_PUBLIC_ORCHESTRATOR_HOST: process.env.NEXT_PUBLIC_ORCHESTRATOR_HOST,
  NEXT_PUBLIC_ORCHESTRATOR_PORT: process.env.NEXT_PUBLIC_ORCHESTRATOR_PORT,
  NEXT_PUBLIC_ORCHESTRATOR_PATH_PREFIX:
    process.env.NEXT_PUBLIC_ORCHESTRATOR_PATH_PREFIX,
  NEXT_PUBLIC_ORCHESTRATOR_TIMEOUT: process.env.NEXT_PUBLIC_ORCHESTRATOR_TIMEOUT,
  NEXT_PUBLIC_BACKEND_HOST: process.env.NEXT_PUBLIC_BACKEND_HOST,
  NEXT_PUBLIC_BACKEND_PORT: process.env.NEXT_PUBLIC_BACKEND_PORT,
  NEXT_PUBLIC_BACKEND_PATH_PREFIX: process.env.NEXT_PUBLIC_BACKEND_PATH_PREFIX,
  NEXT_PUBLIC_MOTION_FILE_TIMEOUT: process.env.NEXT_PUBLIC_MOTION_FILE_TIMEOUT,
  NEXT_PUBLIC_MAX_FRONT_EXTENSION_DURATION:
    process.env.NEXT_PUBLIC_MAX_FRONT_EXTENSION_DURATION,
  NEXT_PUBLIC_MAX_REAR_EXTENSION_DURATION:
    process.env.NEXT_PUBLIC_MAX_REAR_EXTENSION_DURATION,
  NEXT_PUBLIC_LANGUAGE: process.env.NEXT_PUBLIC_LANGUAGE,
}

export function runtimeEnv(key: string): string | undefined {
  if (process.env.NEXT_PUBLIC_DEPLOY_TARGET === 'github-pages') {
    return staticPublicEnv[key]
  }

  return env(key)
}
